import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/navBar'
import Header from './cabecera'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <div className='bg-slate-900 text-[#C0BCB5]'>
          <div className="mx-auto max-w-screen-xl px-4">
            <Header />
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
